#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/Hasbun_Michelle_Pong_Final.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/core.jar:$APPDIR/lib/net.jar" Hasbun_Michelle_Pong_Final "$@"
