/* autogenerated by Processing revision 1292 on 2023-10-15 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.net.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class LEAFFFFF extends PApplet {

//Due 15th


//Global Variables

//Variables for the server.
Client c;
String data;

//initialize
PImage tree; 
PImage cloud;
PImage mLeaf;
PVector leafInitloc; 
int leafState;
int leafCurrentframe = 0;
int leafCount;
int lY = -1;
int lX = 10;
float leafEnd;
int xPos = -300;
int xDir = 2;

Leaf[] leaves; //leaf array

PShape hand;

public void setup() {
  /* size commented out by preprocessor */; //screen size
  //int setX = int((displayWidth - width) / 2);
  //int setY = int((displayHeight - height) / 2);
  //surface.setSize(1000, 900);
  //surface.setLocation(int((displayWidth - width) / 2), int((displayHeight - height) / 2));
  
  translate(PApplet.parseInt(displayWidth - width) / 2, PApplet.parseInt(displayHeight - height) / 2);
  
  tree = loadImage("./data/tree2.png"); //load image of tree 
  cloud = loadImage("./data/cloud.png"); //load image of cloud
  mLeaf = loadImage("./data/leaf2.png");
  leafInitloc = new PVector(0,0); //initial P Vector (leaf)
  leafState = 0; //if mouse has been pressed (leaf)
  leafCount = 0; // leaf count
  leaves = new Leaf[100]; //array of leaf object
  frameRate(45);
  leafEnd = 0; //end of movement (leaf)
  
  hand = loadShape("data/Hand.svg");
  
   //Connect to the server for the mouse position.
  c = new Client(this, "localhost", 9999);
}

float myMouseY = -100;

float myMouseX = -100;

public void draw() {
   if(millis() >= 30000){
      print("Done");
      exit();
   }
    if (c.available() > 0) {
    // read the data from the client
    data = c.readString();
    //Split the msg.
    String[] xy = split(data, ',');
    
    float x = PApplet.parseFloat(xy[0]);
    float y  = PApplet.parseFloat(xy[1]);
    
    
    //Set the mouse position to the data from the server.
    myMouseX = PApplet.parseInt(map(PApplet.parseInt(x),0,640,0,width));
    myMouseY = PApplet.parseInt(map(PApplet.parseInt(y),0,480,0,height));
  }
    
   background(0xFFD9F5FC); //background sky
   fill(0xFFF2F284);
   noStroke();
   ellipse(100,100,280,280);
   
    
   image(cloud, xPos, -130, 400, 400); //cloud start position and size
    xPos = xPos + 3; //movement of cloud
     if (xPos > width) { //cloud bounds
     xPos = -300; //restart poition
  }
  
  image(tree,0,0); //draw background image
  
  println(mouseX+","+mouseY); //print mouse location
  
 // if pressed within x and y coordinate bounds, smooths out how many leaves appear with each click:
  if(frameCount - leafCurrentframe > 40){ 
   
     if(myMouseX > 246 && myMouseX < 718 && myMouseY > 79 && myMouseY < 407) { //bounds of tree where mouse pressed mmakes leaves appear
     
      PVector tempLoc = new PVector(myMouseX,myMouseY); 
      leaves[leafCount] = new Leaf(tempLoc,mLeaf);
      leafCount++;
      leafCurrentframe = frameCount;
     
    }
  
}
  
  if(leafCount > 0){ //if leaf count is greater than zero (mouse has been pressed)
    for(int i = 0; i < leafCount; i++){
     leafEnd = SelectRandom(); //random end position 
      if(leaves[i].Loc.y + leaves[i].y < leafEnd) {
       leaves[i].Update(); //update
      } else {
        leaves[i].done = true; //done falling
      }
        leaves[i].DisplayLeaf(); //leaf display
    }
  }
  
  shape(hand,myMouseX,myMouseY,hand.width/6,hand.height/6); 
  
}

public float SelectRandom() { //random end position
  return random(760,900);
}

public void checktime(){
   
  if(millis() > 30000){
   print("Done");
    exit();
  }
}
 




  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
class Leaf {
  //initialize
  PImage leaf;
  PVector Loc; 
  int x = 10;
  int y = -1;
  boolean done; 
  
  Leaf(PVector _location, PImage _leaf) { //location
    Loc = _location; 
    leaf = _leaf; //load image of leaf
    done = false; //if leaf is not done falling
  }
  
  public void Update() { //update
    if(done == false){ // if leaf is not done falling
    y = y + 2; //leafs movement on the y axis
    x = PApplet.parseInt(cos(radians(y*5))*50);// leafs movement on the x axis
    }
    
   
  } 
  
  public void DisplayLeaf() {
    
       image(leaf, Loc.x + x, Loc.y + y, 100, 75); //image of leaf appears at mouse x and y location
     
  }
  

}


  public void settings() { size(1000, 900); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "LEAFFFFF" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
